//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enovel.Canacol.FacturacionElectronica.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class tblFechasFacturacion
    {
        private int periodo;
        public int ID { get; set; }
        [Display(Name = "Año")]
        public int Periodo
        {
            get
            {
                return DateTime.Now.Year;
            }
            set
            {
                periodo = value;
            }
        }
        public System.DateTime Enero { get; set; }
        public System.DateTime Febrero { get; set; }
        public System.DateTime Marzo { get; set; }
        public System.DateTime Abril { get; set; }
        public System.DateTime Mayo { get; set; }
        public System.DateTime Junio { get; set; }
        public System.DateTime Julio { get; set; }
        public System.DateTime Agosto { get; set; }
        public System.DateTime Septiembre { get; set; }
        public System.DateTime Octubre { get; set; }
        public System.DateTime Noviembre { get; set; }
        public System.DateTime Diciembre { get; set; }
    }
}
