//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enovel.Canacol.FacturacionElectronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGoodReceiptRadicado
    {
        public int ID { get; set; }
        public int IDRadicado { get; set; }
        public int IDGoodReceipt { get; set; }
    
        public virtual tblGoodReceiptProveedor tblGoodReceiptProveedor { get; set; }
        public virtual tblRadicado tblRadicado { get; set; }
    }
}
