//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enovel.Canacol.FacturacionElectronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNumeroOrdenProveedor
    {
        public int IDTipoOrden { get; set; }
        public int IDEmpresaPorProveedor { get; set; }
        public string NumeroOrden { get; set; }
    
        public virtual tblEmpresaPorProveedor tblEmpresaPorProveedor { get; set; }
        public virtual tblTipoOrden tblTipoOrden { get; set; }
    }
}
