//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enovel.Canacol.FacturacionElectronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRut
    {
        public int ID { get; set; }
        public Nullable<int> IDUsuarioProveedor { get; set; }
        public string Nombre { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
    
        public virtual tblUsuariosProveedor tblUsuariosProveedor { get; set; }
    }
}
