//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enovel.Canacol.FacturacionElectronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRadicado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRadicado()
        {
            this.tblGoodReceiptRadicado = new HashSet<tblGoodReceiptRadicado>();
        }
    
        public int ID { get; set; }
        public string NumeroRadicado { get; set; }
        public Nullable<int> IDProveedor { get; set; }
        public string RutaArchivoOrden { get; set; }
        public string RutaArchivoGoodReceipt { get; set; }
        public string Soporte1 { get; set; }
        public string Soporte2 { get; set; }
        public string Soporte3 { get; set; }
        public string Soporte4 { get; set; }
        public string Soporte5 { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<decimal> ValorFactura { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<decimal> ValorAntesIVA { get; set; }
        public Nullable<decimal> ValorDespuesIVA { get; set; }
        public string RutaFactura { get; set; }
        public string RutaXMLFactura { get; set; }
        public string Observaciones { get; set; }
        public string NumeroCausacion { get; set; }
        public string RutaArchivoCausacion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodReceiptRadicado> tblGoodReceiptRadicado { get; set; }
        public virtual tblUsuariosProveedor tblUsuariosProveedor { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
    }
}
