//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enovel.Canacol.FacturacionElectronica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUsuariosProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsuariosProveedor()
        {
            this.tblRadicadoes = new HashSet<tblRadicado>();
            this.UsuarioActivacions = new HashSet<UsuarioActivacion>();
        }
    
        public int ID { get; set; }

        [DisplayName("Usuario")]
        [Required(ErrorMessage = "El usuario es requerido")]
        public string UsuarioNit { get; set; }

        [DisplayName("Clave")]
        [Required(ErrorMessage = "La clave es requerida")]
        public string Password { get; set; }

        [DisplayName("Clave")]
        [Required(ErrorMessage = "La clave es requerida")]
        public string ConfirmarPassword { get; set; }

        public string RazonSocial { get; set; }
        public Nullable<int> IDCalidadTributaria { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string RepresentanteLegal { get; set; }
        public string RutaRut { get; set; }
        public string RutaCamaraComercio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string LoginErrorMessage { get; set; }
        public virtual tblCalidadTributaria tblCalidadTributaria { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRadicado> tblRadicadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioActivacion> UsuarioActivacions { get; set; }
    }
}
